import './globals.css'
import Head from 'next/head'
import NavBar from './component/NavBar'

export const metadata = {
  title: 'portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css"  rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
      </Head>
      <body className="h-[100vh] flex flex-col relative w-full overflow-hidden bg-gray-900 overflow-y-auto" >
      <NavBar/>
      {children}</body>
    </html>
  )
}
