import './globals.css'
import Head from 'next/head'
import NavBar from './component/NavBar'

export const metadata = {
  title: 'portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Jacquard+24&display=swap" rel="stylesheet"></link>
      </Head>
      <body className="h-[100vh] flex flex-col relative w-full overflow-hidden bg-gray-900 overflow-y-auto" >
        <NavBar />
        {children}</body>
    </html>
  )
}
