import './globals.css'
import Head from 'next/head'

export const metadata = {
  title: 'portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:wght@600&family=Kreon:wght@600&family=Libertinus+Sans:ital,wght@0,400;0,700;1,400&family=Rowdies:wght@300;400&display=swap" rel="stylesheet"></link>
      </head>

      <body className="h-[100vh] flex flex-col relative w-full overflow-hidden bg-gray-900 overflow-y-auto" >
        {children}
      </body>
    </html>
  )
}
